### ISSUE TITLE
Does this work with uasyncio v3?

### ISSUE THREAD

**Issue by pgcudahy** [shawwwn/micropython-ainput#1]
I'm having some issues getting this to work, not sure whether it's me or the changes since `v3` (https://forum.micropython.org/viewtopic.php?t=8148&p=46311) such as `call_soon` no longer being implemented.

**Comment by shawwwn** [comment]
I think you can use other methods (such as `create_task`) to substitute `call_soon` as the work function is nothing more than a coroutine.

To getting this module to work you need your micropython to support polling data from UART0 while the main thread is blocking. 
Some implementations of micropython let you do this, some don't.
You can check it via running these two commands in the REPL console.
https://github.com/shawwwn/micropython-ainput/blob/5d3ba59edb5e83100f1c3d7c4954822a6c1d866c/uaioinput.py#L18-L19

**Comment by shawwwn** [comment]
closed due to inactivity
